# -*- coding: utf-8 -*-
"""Pothole Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXhdHGCWDkLF72rtC755isn6_nVl6yde

## **🚀 📘 NOTEBOOK: Pothole Detection (YOLOv8 + RDD2022)**

🧱 1. Setup Environment
"""

# Install dependencies
!pip install -q ultralytics kaggle opencv-python matplotlib

# Restart runtime after this if needed

"""🔐 2. Kaggle API Setup"""

import os

os.makedirs("/root/.kaggle", exist_ok=True)
!cp kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

"""📥 3. Download Dataset (RDD2022 Clean Split)"""

# Download dataset
!kaggle datasets download -d aliabdelmenam/rdd-2022

# Unzip
!unzip -q rdd-2022.zip -d data

"""📂 4. Verify Dataset Structure"""

import os

base_path = "/content/data/RDD_SPLIT"

for split in ["train", "val", "test"]:
    print(f"\n🔹 {split.upper()}")
    print("Images:", len(os.listdir(f"{base_path}/{split}/images")))
    print("Labels:", len(os.listdir(f"{base_path}/{split}/labels")))

"""🔍 5. Inspect Labels (Class Mapping Check)"""

label_path = f"{base_path}/train/labels"

for file in os.listdir(label_path)[:5]:
    print(f"\n📄 {file}")
    with open(os.path.join(label_path, file)) as f:
        print(f.read())

"""🧹 6. Filter Only Potholes (D40 → class 0)"""

for split in ["train", "val"]:
    label_dir = f"{base_path}/{split}/labels"

    for file in os.listdir(label_dir):
        file_path = os.path.join(label_dir, file)

        with open(file_path, "r") as f:
            lines = f.readlines()

        new_lines = []
        for line in lines:
            parts = line.strip().split()
            class_id = int(parts[0])

            if class_id == 3:  # pothole
                parts[0] = "0"
                new_lines.append(" ".join(parts))

        with open(file_path, "w") as f:
            f.write("\n".join(new_lines))

"""🧼 7. Remove Empty Labels + Images"""

for split in ["train", "val"]:
    label_dir = f"{base_path}/{split}/labels"
    image_dir = f"{base_path}/{split}/images"

    for file in os.listdir(label_dir):
        file_path = os.path.join(label_dir, file)

        if os.path.getsize(file_path) == 0:
            os.remove(file_path)

            img_file = file.replace(".txt", ".jpg")
            img_path = os.path.join(image_dir, img_file)

            if os.path.exists(img_path):
                os.remove(img_path)

"""📊 8. Visualize Sample Images"""

import cv2
import matplotlib.pyplot as plt
import random

def show_sample():
    img_dir = f"{base_path}/train/images"
    label_dir = f"{base_path}/train/labels"

    file = random.choice(os.listdir(img_dir))
    img_path = os.path.join(img_dir, file)
    label_path = os.path.join(label_dir, file.replace(".jpg", ".txt"))

    img = cv2.imread(img_path)
    h, w, _ = img.shape

    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f:
                _, x, y, bw, bh = map(float, line.split())

                x1 = int((x - bw/2) * w)
                y1 = int((y - bh/2) * h)
                x2 = int((x + bw/2) * w)
                y2 = int((y + bh/2) * h)

                cv2.rectangle(img, (x1,y1), (x2,y2), (0,255,0), 2)

    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.axis("off")

show_sample()

"""⚙️ 9. Create data.yaml"""

yaml_content = """
path: /content/data/RDD_SPLIT

train: train/images
val: val/images

names:
  0: pothole
"""

with open("data.yaml", "w") as f:
    f.write(yaml_content)

"""🤖 10. Train YOLO Model"""

from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # start small

model.train(
    data="data.yaml",
    epochs=30,
    imgsz=640,
    batch=16
)

"""📈 11. Evaluate Model"""

metrics = model.val()
print(metrics)

"""📦 12. Save / Export Model"""

# Best weights path
model_path = "/content/runs/detect/train/weights/best.pt"

print("Model saved at:", model_path)

"""🔄 13. Export to Different Formats (for Web/App)"""

model.export(format="onnx")
model.export(format="tflite")
model.export(format="torchscript")

"""🌐 14. Minimal Inference Function (Web Ready)"""

def detect_potholes(image_path):
    results = model(image_path)
    return results[0].plot()

"""🧪 15. SANITY CHECK (Upload Image & Test)"""

from google.colab import files
from PIL import Image

uploaded = files.upload()

for file in uploaded.keys():
    result = model(file,conf=0.05)

    img = result[0].plot()
    plt.imshow(img)
    plt.axis("off")

import shutil
import os

output_zip_path = 'yolov8n_pothole_model_exports.zip'
model_exports_dir = '/content/runs/detect/train/weights'

# Create a zip archive of the model exports directory
shutil.make_archive(os.path.splitext(output_zip_path)[0], 'zip', model_exports_dir)

print(f"All model files (best.pt, onnx, tflite, torchscript) have been zipped to: {output_zip_path}")

from google.colab import files

# Offer the zip file for download
files.download(output_zip_path)