# -*- coding: utf-8 -*-
"""Road_Damage_MultiModel_Pipeline (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYjfGlssjbgf-TT79yOuPFqcUKEpoHLU

# 🚧 AI-Powered Road Damage Detection — Multi-Model Pipeline

**Models:** 3 YOLOv8s models trained on different POV datasets  
**Framework:** PyTorch (Ultralytics YOLOv8)  
**Runtime:** Google Colab T4 GPU  

| Model | Dataset | POV | Strategy |
|-------|---------|-----|----------|
| **Model A** | RDD2022 | Dashcam / moving vehicle | Train from COCO pretrained |
| **Model B** | Pothole-600 | Close-up / inspection | Fine-tune from Model A |
| **Model C** | Kaggle Annotated Potholes | Street / pedestrian | Fine-tune from Model B |

> **Transfer chain:** `COCO → model_a → model_b → model_c`  
> Each model inherits road-damage knowledge from the previous one.

---

## ⚙️ Section 0 — Setup
"""

# CELL 1 — Install Dependencies
# Run this cell first. Restart runtime if prompted.

!pip install ultralytics roboflow --quiet
!pip install opencv-python-headless scikit-learn --quiet

import ultralytics
ultralytics.checks()  # Confirms GPU is available and versions

# CELL 2 — Mount Google Drive
# Critical: We save each model to Drive immediately after training.
# If Colab disconnects mid-run, your weights are safe.

from google.colab import drive
drive.mount('/content/drive')

import os

DRIVE_SAVE_DIR = '/content/drive/MyDrive/RoadDamageAI/weights'
os.makedirs(DRIVE_SAVE_DIR, exist_ok=True)

print(f'✓ Drive mounted. Weights will be saved to: {DRIVE_SAVE_DIR}')

# CELL 3 — GPU Check + Global Config

import torch

print('=' * 50)
print(f'PyTorch version : {torch.__version__}')
print(f'CUDA available  : {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'GPU             : {torch.cuda.get_device_name(0)}')
    print(f'VRAM            : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')
print('=' * 50)

# ── Global Paths ─────────────────────────────────────────────────────
WORKSPACE = '/content/road_damage_ai'
os.makedirs(WORKSPACE, exist_ok=True)

MODEL_A_PATH = f'{DRIVE_SAVE_DIR}/model_a_rdd2022.pt'
MODEL_B_PATH = f'{DRIVE_SAVE_DIR}/model_b_pothole600.pt'
MODEL_C_PATH = f'{DRIVE_SAVE_DIR}/model_c_kaggle.pt'

# ── Training Config ───────────────────────────────────────────────────
# T4 has 15GB VRAM. YOLOv8s at batch=16, imgsz=640 fits comfortably.
TRAIN_CONFIG = {
    'imgsz'   : 640,
    'batch'   : 16,
    'workers' : 2,
    'device'  : 0,       # GPU 0
    'patience': 15,      # Early stopping
    'save'    : True,
    'plots'   : True,
    'verbose' : True,
}

print('\n✓ Global config set.')
print(f"  Image size : {TRAIN_CONFIG['imgsz']}")
print(f"  Batch size : {TRAIN_CONFIG['batch']}")
print(f"  Device     : GPU {TRAIN_CONFIG['device']}")

# CELL 4 — Resume Check Helper
# If a model already exists on Drive, skip training and reload.
# Makes the notebook safely resumable after a Colab disconnect.

import shutil

def model_exists_on_drive(path):
    exists = os.path.exists(path)
    if exists:
        size_mb = os.path.getsize(path) / 1e6
        print(f'✓ Found existing model: {path} ({size_mb:.1f} MB) — skipping training.')
    return exists

def save_model_to_drive(source_path, dest_path):
    shutil.copy2(source_path, dest_path)
    size_mb = os.path.getsize(dest_path) / 1e6
    print(f'✓ Saved to Drive: {dest_path} ({size_mb:.1f} MB)')

print('✓ Helper functions ready.')

"""---
## 🔴 Model A — Dashcam POV (RDD2022)

- **Dataset:** Road Damage Detection Challenge 2022
- **Source:** Roboflow Universe
- **Classes:** D00 (longitudinal crack), D10 (transverse crack), D20 (alligator crack), D40 (pothole)
- **Strategy:** Train from pretrained COCO YOLOv8s weights

### How to get your Roboflow API key:
1. Go to [roboflow.com](https://roboflow.com) → Sign up (free)
2. Settings → Roboflow API → copy your **Private API Key**
3. Go to [universe.roboflow.com](https://universe.roboflow.com) → search **RDD2022**
4. Click the dataset → Download → YOLOv8 → **Show Download Code**
5. Copy `workspace`, `project`, `version` values → paste below
"""

# CELL A1 — Download RDD2022 via Roboflow
# ⚠️  REPLACE the values below before running

from roboflow import Roboflow

ROBOFLOW_API_KEY = '1aCLMrgfzCjegea4Tx3j'   # ← Paste your API key here
RDD2022_WORKSPACE = 'segmentpavementdiseases'               # ← From Roboflow dataset page
RDD2022_PROJECT   = 'rdd2022-shuvm'               # ← From Roboflow dataset page
RDD2022_VERSION   = 2                        # ← Version number

rf = Roboflow(api_key=ROBOFLOW_API_KEY)
project_a  = rf.workspace(RDD2022_WORKSPACE).project(RDD2022_PROJECT)
dataset_a  = project_a.version(RDD2022_VERSION).download('yolov8', location=f'{WORKSPACE}/dataset_a')

DATASET_A_YAML = f'{WORKSPACE}/dataset_a/data.yaml'
print(f'\n✓ RDD2022 downloaded.')
print(f'  YAML: {DATASET_A_YAML}')

# CELL A2 — Inspect Dataset A

import yaml
from pathlib import Path

with open(DATASET_A_YAML, 'r') as f:
    data_a = yaml.safe_load(f)

print('Dataset A — RDD2022 Config:')
print(f"  Classes : {data_a.get('nc')} → {data_a.get('names')}")

train_dir = Path(DATASET_A_YAML).parent / 'train' / 'images'
val_dir   = Path(DATASET_A_YAML).parent / 'valid' / 'images'
train_count = len(list(train_dir.glob('*.jpg'))) + len(list(train_dir.glob('*.png')))
val_count   = len(list(val_dir.glob('*.jpg')))   + len(list(val_dir.glob('*.png')))

print(f'  Train   : {train_count} images')
print(f'  Val     : {val_count} images')
print(f'  Total   : {train_count + val_count} images')

# CELL A3 — Train Model A

from ultralytics import YOLO

if model_exists_on_drive(MODEL_A_PATH):
    model_a = YOLO(MODEL_A_PATH)
else:
    print('Starting Model A training: YOLOv8s on RDD2022...')
    print('Estimated time on T4: ~35-45 minutes for 50 epochs\n')

    model_a = YOLO('yolov8s.pt')  # Start from COCO pretrained weights

    results_a = model_a.train(
        data    = DATASET_A_YAML,
        epochs  = 50,
        name    = 'model_a_rdd2022',
        project = f'{WORKSPACE}/runs',
        **TRAIN_CONFIG,
    )

    best_weights_a = f'{WORKSPACE}/runs/model_a_rdd2022/weights/best.pt'
    save_model_to_drive(best_weights_a, MODEL_A_PATH)
    model_a = YOLO(MODEL_A_PATH)

print('\n✓ Model A ready.')

# CELL A4 — Evaluate Model A

print('Evaluating Model A on validation set...')
metrics_a = model_a.val(data=DATASET_A_YAML, verbose=True)

print('\n── Model A Results ──────────────────')
print(f'  mAP50     : {metrics_a.box.map50:.4f}')
print(f'  mAP50-95  : {metrics_a.box.map:.4f}')
print(f'  Precision : {metrics_a.box.mp:.4f}')
print(f'  Recall    : {metrics_a.box.mr:.4f}')
print('─────────────────────────────────────')

"""---
## 🟢 Model B — Close-up / Inspection POV (Pothole-600)

- **Dataset:** Pothole-600
- **Source:** Roboflow Universe
- **Classes:** pothole (1 class)
- **Strategy:** Fine-tune **from model_a.pt** — inherits road-damage knowledge, specializes on potholes

### How to get Pothole-600:
1. Go to [universe.roboflow.com](https://universe.roboflow.com) → search **Pothole-600**
2. Click Download → YOLOv8 → **Show Download Code**
3. Copy `workspace`, `project`, `version` → paste below
"""

# CELL B1 — Download Pothole-600 via Roboflow
# ⚠️  REPLACE workspace/project/version values below

POTHOLE_WORKSPACE = 'yeeun-kim-fyvoj'   # ← From Roboflow dataset page
POTHOLE_PROJECT   = 'pothole-vhmow'     # ← From Roboflow dataset page
POTHOLE_VERSION   = 18                  # ← Version number

# Reuse same Roboflow API key from Cell A1
rf_b      = Roboflow(api_key=ROBOFLOW_API_KEY)
project_b = rf_b.workspace(POTHOLE_WORKSPACE).project(POTHOLE_PROJECT)
dataset_b = project_b.version(POTHOLE_VERSION).download('yolov8', location=f'{WORKSPACE}/dataset_b')

DATASET_B_YAML = f'{WORKSPACE}/dataset_b/data.yaml'
print(f'\n✓ Pothole-600 downloaded.')
print(f'  YAML: {DATASET_B_YAML}')

# CELL B2-NUCLEAR — Verify, fix, and confirm everything before B3

import os, shutil, yaml, random
from pathlib import Path

DATASET_B_ROOT = Path(f'{WORKSPACE}/dataset_b')

# ── Step 1: Show exactly what's on disk right now ─────────────────────
print("=== CURRENT DISK STATE ===")
for p in sorted(DATASET_B_ROOT.rglob('*')):
    if p.is_dir():
        files = list(p.glob('*.*'))
        print(f"  DIR : {p.relative_to(DATASET_B_ROOT)}/ ({len(files)} files)")
print()

# ── Step 2: Read current YAML ─────────────────────────────────────────
yaml_path = DATASET_B_ROOT / 'data.yaml'
with open(yaml_path) as f:
    current = yaml.safe_load(f)
print("=== CURRENT YAML CONTENTS ===")
print(current)
print()

# ── Step 3: Create valid/images and valid/labels if missing ───────────
train_img = DATASET_B_ROOT / 'train' / 'images'
train_lbl = DATASET_B_ROOT / 'train' / 'labels'
valid_img  = DATASET_B_ROOT / 'valid' / 'images'
valid_lbl  = DATASET_B_ROOT / 'valid' / 'labels'

valid_img.mkdir(parents=True, exist_ok=True)
valid_lbl.mkdir(parents=True, exist_ok=True)

# Only split if valid is still empty
existing_val = list(valid_img.glob('*.jpg')) + list(valid_img.glob('*.png'))
if len(existing_val) == 0:
    all_imgs = list(train_img.glob('*.jpg')) + list(train_img.glob('*.png'))
    paired = [img for img in all_imgs if (train_lbl / f'{img.stem}.txt').exists()]

    random.seed(42)
    random.shuffle(paired)
    n_val = max(10, int(len(paired) * 0.2))
    val_imgs = paired[:n_val]

    for img_path in val_imgs:
        shutil.move(str(img_path), valid_img / img_path.name)
        lbl_path = train_lbl / f'{img_path.stem}.txt'
        if lbl_path.exists():
            shutil.move(str(lbl_path), valid_lbl / f'{img_path.stem}.txt')

    print(f"✓ Created val split: {n_val} images moved to valid/images")
else:
    print(f"✓ valid/images already has {len(existing_val)} files — skipping split")

# ── Step 4: Force-overwrite YAML with absolute paths ─────────────────
# Do NOT use relative paths — Ultralytics resolves relative to 'path' key
new_yaml = {
    'path'  : str(DATASET_B_ROOT.resolve()),
    'train' : 'train/images',
    'val'   : 'valid/images',
    'nc'    : 1,
    'names' : ['pothole'],
}

with open(yaml_path, 'w') as f:
    yaml.dump(new_yaml, f, default_flow_style=False, sort_keys=False)

# ── Step 5: Verify YAML was written correctly ─────────────────────────
with open(yaml_path) as f:
    verified = yaml.safe_load(f)
print("\n=== YAML AFTER FIX ===")
print(verified)

# ── Step 6: Verify the resolved paths actually exist ─────────────────
resolved_train = DATASET_B_ROOT.resolve() / 'train' / 'images'
resolved_val   = DATASET_B_ROOT.resolve() / 'valid' / 'images'

train_count = len(list(resolved_train.glob('*.jpg')) + list(resolved_train.glob('*.png')))
val_count   = len(list(resolved_val.glob('*.jpg'))   + list(resolved_val.glob('*.png')))

print(f"\n=== PATH VERIFICATION ===")
print(f"  train/images exists : {resolved_train.exists()} → {train_count} images")
print(f"  valid/images exists : {resolved_val.exists()} → {val_count} images")

# ── Step 7: Update the global variable ───────────────────────────────
DATASET_B_YAML = str(yaml_path)
print(f"\n✓ DATASET_B_YAML = {DATASET_B_YAML}")

if resolved_train.exists() and resolved_val.exists() and train_count > 0 and val_count > 0:
    print("\n✅ ALL CHECKS PASSED — Safe to run Cell B3 now")
else:
    print("\n❌ STILL BROKEN — paste the output above so we can debug further")

# CELL B2b — Diagnose Dataset B folder structure
import os

print("Actual folder structure of dataset_b:")
for root, dirs, files in os.walk(f'{WORKSPACE}/dataset_b'):
    level = root.replace(f'{WORKSPACE}/dataset_b', '').count(os.sep)
    indent = '  ' * level
    print(f'{indent}{os.path.basename(root)}/')
    if level < 2:
        for f in files:
            print(f'{indent}  {f}')

print("\nContent of data.yaml:")
with open(DATASET_B_YAML, 'r') as f:
    print(f.read())

# CELL B2c — Fix dataset_b data.yaml to match actual folder structure
import yaml
from pathlib import Path

dataset_b_root = Path(WORKSPACE) / 'dataset_b'

# Find where the actual images are
def find_split_dir(root, split_names):
    """Try multiple possible folder names for a split."""
    for name in split_names:
        for subdir in ['images', '']:
            candidate = root / name / 'images' if subdir == 'images' else root / name
            if candidate.exists() and any(candidate.glob('*.jpg')) or \
               candidate.exists() and any(candidate.glob('*.png')):
                return str(candidate.relative_to(root))
    return None

train_path = find_split_dir(dataset_b_root, ['train', 'training'])
val_path   = find_split_dir(dataset_b_root, ['valid', 'val', 'validation', 'test'])

print(f"Found train images at : {train_path}")
print(f"Found val images at   : {val_path}")

if not train_path or not val_path:
    # Fallback: list everything and let you decide
    print("\nCould not auto-detect. All image files found:")
    for p in dataset_b_root.rglob('*.jpg'):
        print(f"  {p.relative_to(dataset_b_root)}")
else:
    # Rewrite the YAML with correct paths
    fixed_yaml = {
        'path'  : str(dataset_b_root),
        'train' : train_path,
        'val'   : val_path,
        'nc'    : 1,
        'names' : ['pothole'],
    }

    with open(DATASET_B_YAML, 'w') as f:
        yaml.dump(fixed_yaml, f, default_flow_style=False)

    print(f"\n✓ data.yaml rewritten:")
    print(f"  path  : {fixed_yaml['path']}")
    print(f"  train : {fixed_yaml['train']}")
    print(f"  val   : {fixed_yaml['val']}")
    print(f"\nNow re-run Cell B3.")

# CELL B3 — Fine-tune Model B from model_a.pt
# KEY: We load model_a.pt, NOT yolov8s.pt
# The model already knows road damage — now we specialize it on close-up potholes.

if model_exists_on_drive(MODEL_B_PATH):
    model_b = YOLO(MODEL_B_PATH)
else:
    print('Fine-tuning Model B from model_a.pt on Pothole-600...')
    print('Transfer chain: COCO → RDD2022 → Pothole-600 (current)')
    print('Estimated time on T4: ~15-20 minutes for 30 epochs\n')

    model_b = YOLO(MODEL_A_PATH)   # ← Start from Model A, not COCO

    results_b = model_b.train(
        data    = DATASET_B_YAML,
        epochs  = 30,       # Fewer epochs — fine-tuning, not from scratch
        lr0     = 0.001,    # Lower LR for fine-tuning
        lrf     = 0.01,
        name    = 'model_b_pothole600',
        project = f'{WORKSPACE}/runs',
        **TRAIN_CONFIG,
    )

    best_weights_b = f'{WORKSPACE}/runs/model_b_pothole600/weights/best.pt'
    save_model_to_drive(best_weights_b, MODEL_B_PATH)
    model_b = YOLO(MODEL_B_PATH)

print('\n✓ Model B ready.')

# CELL B3-SAVE-FIX — Model trained fine, just save the right folder

import glob

# Find the actual weights folder Ultralytics created
candidates = glob.glob(f'{WORKSPACE}/runs/model_b_pothole600*/weights/best.pt')
candidates.sort()  # Latest is last

print("Found weight files:")
for c in candidates:
    print(f"  {c}")

# Take the most recent one
actual_best = candidates[-1]
print(f"\nUsing: {actual_best}")

save_model_to_drive(actual_best, MODEL_B_PATH)
model_b = YOLO(MODEL_B_PATH)

print("\n✅ Model B saved to Drive successfully!")
print(f"   mAP50: 0.885 — strong result for 30 epochs fine-tuning")

# CELL B4 — Evaluate Model B

print('Evaluating Model B on validation set...')
metrics_b = model_b.val(data=DATASET_B_YAML, verbose=True)

print('\n── Model B Results ──────────────────')
print(f'  mAP50     : {metrics_b.box.map50:.4f}')
print(f'  mAP50-95  : {metrics_b.box.map:.4f}')
print(f'  Precision : {metrics_b.box.mp:.4f}')
print(f'  Recall    : {metrics_b.box.mr:.4f}')
print('─────────────────────────────────────')

"""---
## 🔵 Model C — Street / Pedestrian POV (Kaggle)

- **Dataset:** Annotated Potholes Dataset (`chitholian/annotated-potholes-dataset`)
- **Source:** Kaggle
- **Classes:** pothole (1 class)
- **Format:** PASCAL VOC XML → needs conversion to YOLO format
- **Strategy:** Fine-tune **from model_b.pt** — cascaded transfer learning

### Before running:
Have your `kaggle.json` file ready. Cell C1 will ask you to upload it.
"""

# CELL C1 — Upload Kaggle Credentials
# Run this cell → click the file picker → select kaggle.json

from google.colab import files
import json

print('Please upload your kaggle.json file:')
uploaded = files.upload()

os.makedirs(os.path.expanduser('~/.kaggle'), exist_ok=True)
kaggle_path = os.path.expanduser('~/.kaggle/kaggle.json')

with open(kaggle_path, 'w') as f:
    json.dump(json.loads(list(uploaded.values())[0]), f)

os.chmod(kaggle_path, 0o600)
print('\n✓ Kaggle credentials configured.')

# CELL C2 — Download Kaggle Pothole Dataset

DATASET_C_DIR = f'{WORKSPACE}/dataset_c_raw'
os.makedirs(DATASET_C_DIR, exist_ok=True)

print('Downloading annotated potholes dataset from Kaggle...')
!kaggle datasets download -d chitholian/annotated-potholes-dataset -p {DATASET_C_DIR} --unzip

print(f'\n✓ Download complete. Inspecting structure...')
!find {DATASET_C_DIR} -maxdepth 3 | head -40

# CELL C3 — Convert PASCAL VOC XML → YOLO Format
# The Kaggle dataset uses XML annotations (PASCAL VOC).
# YOLO requires: class x_center y_center width height (normalized to [0,1])

import xml.etree.ElementTree as ET
from sklearn.model_selection import train_test_split

def convert_xml_to_yolo(xml_path, class_map):
    """Convert a single PASCAL VOC XML file to YOLO format lines."""
    try:
        tree  = ET.parse(xml_path)
        root  = tree.getroot()
        size  = root.find('size')
        img_w = int(size.find('width').text)
        img_h = int(size.find('height').text)

        if img_w == 0 or img_h == 0:
            return []

        lines = []
        for obj in root.findall('object'):
            cls_name = obj.find('name').text.strip().lower()
            if 'pothole' in cls_name or 'pot' in cls_name:
                cls_name = 'pothole'
            if cls_name not in class_map:
                continue

            cls_id = class_map[cls_name]
            bbox   = obj.find('bndbox')
            xmin   = max(0, min(float(bbox.find('xmin').text), img_w))
            ymin   = max(0, min(float(bbox.find('ymin').text), img_h))
            xmax   = max(0, min(float(bbox.find('xmax').text), img_w))
            ymax   = max(0, min(float(bbox.find('ymax').text), img_h))

            if xmax <= xmin or ymax <= ymin:
                continue

            x_center = (xmin + xmax) / 2 / img_w
            y_center = (ymin + ymax) / 2 / img_h
            width    = (xmax - xmin) / img_w
            height   = (ymax - ymin) / img_h

            lines.append(f'{cls_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}')

        return lines
    except Exception as e:
        print(f'  Warning: Failed to parse {xml_path}: {e}')
        return []


def build_yolo_dataset_c(raw_dir, output_dir):
    CLASS_MAP = {'pothole': 0}
    xml_files = list(Path(raw_dir).rglob('*.xml'))
    print(f'Found {len(xml_files)} XML annotation files')

    valid_pairs = []
    for xml_path in xml_files:
        img_path = None
        for ext in ['.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG']:
            for candidate in [
                xml_path.parent / f'{xml_path.stem}{ext}',
                xml_path.parent.parent / 'images' / f'{xml_path.stem}{ext}'
            ]:
                if candidate.exists():
                    img_path = candidate
                    break
            if img_path:
                break

        if img_path is None:
            continue

        yolo_lines = convert_xml_to_yolo(str(xml_path), CLASS_MAP)
        if yolo_lines:
            valid_pairs.append((img_path, yolo_lines))

    print(f'Valid image-annotation pairs: {len(valid_pairs)}')
    if not valid_pairs:
        raise ValueError('No valid pairs found. Check dataset structure.')

    train_pairs, val_pairs = train_test_split(valid_pairs, test_size=0.2, random_state=42)

    for split_name, pairs in [('train', train_pairs), ('val', val_pairs)]:
        img_out = Path(output_dir) / split_name / 'images'
        lbl_out = Path(output_dir) / split_name / 'labels'
        img_out.mkdir(parents=True, exist_ok=True)
        lbl_out.mkdir(parents=True, exist_ok=True)
        for img_path, yolo_lines in pairs:
            shutil.copy2(img_path, img_out / img_path.name)
            with open(lbl_out / f'{img_path.stem}.txt', 'w') as f:
                f.write('\n'.join(yolo_lines))

    print(f'\n✓ Dataset C prepared:')
    print(f'   Train : {len(train_pairs)} images')
    print(f'   Val   : {len(val_pairs)} images')


DATASET_C_YOLO_DIR = f'{WORKSPACE}/dataset_c_yolo'
build_yolo_dataset_c(DATASET_C_DIR, DATASET_C_YOLO_DIR)

# CELL C4 — Create dataset.yaml for Model C

DATASET_C_YAML = f'{DATASET_C_YOLO_DIR}/data.yaml'

data_c_config = {
    'path'  : DATASET_C_YOLO_DIR,
    'train' : 'train/images',
    'val'   : 'val/images',
    'nc'    : 1,
    'names' : ['pothole'],
}

with open(DATASET_C_YAML, 'w') as f:
    yaml.dump(data_c_config, f, default_flow_style=False)

print(f'✓ dataset.yaml created for Model C')
print(f'  Path    : {DATASET_C_YAML}')
print(f'  Classes : 1 (pothole)')

# CELL C5 — Fine-tune Model C from model_b.pt
# Transfer chain: COCO → RDD2022 → Pothole-600 → Kaggle (current)

if model_exists_on_drive(MODEL_C_PATH):
    model_c = YOLO(MODEL_C_PATH)
else:
    print('Fine-tuning Model C from model_b.pt on Kaggle Potholes...')
    print('Full chain: COCO → RDD2022 → Pothole-600 → Kaggle')
    print('Estimated time on T4: ~10-15 minutes for 25 epochs\n')

    model_c = YOLO(MODEL_B_PATH)   # ← Start from Model B

    results_c = model_c.train(
        data    = DATASET_C_YAML,
        epochs  = 25,
        lr0     = 0.0005,   # Very low LR — heavily fine-tuning
        lrf     = 0.01,
        name    = 'model_c_kaggle',
        project = f'{WORKSPACE}/runs',
        **TRAIN_CONFIG,
    )

    best_weights_c = f'{WORKSPACE}/runs/model_c_kaggle/weights/best.pt'
    save_model_to_drive(best_weights_c, MODEL_C_PATH)
    model_c = YOLO(MODEL_C_PATH)

print('\n✓ Model C ready.')

# CELL C6 — Evaluate Model C

print('Evaluating Model C on validation set...')
metrics_c = model_c.val(data=DATASET_C_YAML, verbose=True)

print('\n── Model C Results ──────────────────')
print(f'  mAP50     : {metrics_c.box.map50:.4f}')
print(f'  mAP50-95  : {metrics_c.box.map:.4f}')
print(f'  Precision : {metrics_c.box.mp:.4f}')
print(f'  Recall    : {metrics_c.box.mr:.4f}')
print('─────────────────────────────────────')

# CELL C7 — All Models Performance Summary

print('\n' + '=' * 58)
print('        ALL MODELS — PERFORMANCE SUMMARY')
print('=' * 58)
print(f"{'Model':<12} {'Dataset':<18} {'mAP50':>7} {'mAP50-95':>9} {'Prec':>6} {'Rec':>6}")
print('-' * 58)
print(f"{'Model A':<12} {'RDD2022':<18} {metrics_a.box.map50:>7.4f} {metrics_a.box.map:>9.4f} {metrics_a.box.mp:>6.4f} {metrics_a.box.mr:>6.4f}")
print(f"{'Model B':<12} {'Pothole-600':<18} {metrics_b.box.map50:>7.4f} {metrics_b.box.map:>9.4f} {metrics_b.box.mp:>6.4f} {metrics_b.box.mr:>6.4f}")
print(f"{'Model C':<12} {'Kaggle':<18} {metrics_c.box.map50:>7.4f} {metrics_c.box.map:>9.4f} {metrics_c.box.mp:>6.4f} {metrics_c.box.mr:>6.4f}")
print('=' * 58)

"""---
## 🔀 Multi-Model Inference Pipeline

All 3 models run on every input image. Predictions are:
1. Collected from all 3 models
2. Merged using **cross-model NMS** to remove duplicates
3. Drawn with **color-coded bounding boxes** per model
4. Displayed with a **confidence + consensus table**

| Color | Model | Dataset |
|-------|-------|---------|
| 🔴 Red | Model A | RDD2022 Dashcam |
| 🟢 Green | Model B | Pothole-600 Close-up |
| 🔵 Blue | Model C | Kaggle Street |
"""

# CELL D1 — Load All 3 Models

from ultralytics import YOLO

print('Loading all 3 models from Drive...')
model_a = YOLO(MODEL_A_PATH)
model_b = YOLO(MODEL_B_PATH)
model_c = YOLO(MODEL_C_PATH)

MODELS = {
    'model_a': {'model': model_a, 'name': 'RDD2022 Dashcam',   'color': (255, 50,  50),  'conf': 0.05},
    'model_b': {'model': model_b, 'name': 'Pothole-600 Close', 'color': (50,  220, 50),  'conf': 0.10},
    'model_c': {'model': model_c, 'name': 'Kaggle Street',     'color': (50,  100, 255), 'conf': 0.05},
}

print('\n✓ All models loaded:')
for mid, info in MODELS.items():
    print(f"  {mid}: {info['name']} (conf threshold: {info['conf']})")

# CELL D2 — Cross-Model NMS
# Merges overlapping detections from all models into one clean output.
# Tracks which models agreed — consensus = high reliability signal.

import numpy as np

def compute_iou(box1, box2):
    """Intersection over Union. Format: [x1, y1, x2, y2] pixels."""
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])
    intersection = max(0, x2 - x1) * max(0, y2 - y1)
    if intersection == 0:
        return 0.0
    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])
    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])
    union = area1 + area2 - intersection
    return intersection / union if union > 0 else 0.0


def cross_model_nms(all_detections, iou_threshold=0.45):
    """NMS across all model predictions. Tracks agreeing models per detection."""
    if not all_detections:
        return []

    sorted_dets = sorted(all_detections, key=lambda x: x['confidence'], reverse=True)
    kept, suppressed = [], set()

    for i, det_i in enumerate(sorted_dets):
        if i in suppressed:
            continue
        det_i['agreeing_models'] = [det_i['model_id']]
        for j, det_j in enumerate(sorted_dets):
            if j <= i or j in suppressed:
                continue
            if compute_iou(det_i['bbox'], det_j['bbox']) > iou_threshold:
                det_i['agreeing_models'].append(det_j['model_id'])
                suppressed.add(j)
        kept.append(det_i)

    return kept

print('✓ Cross-model NMS function ready.')

# CELL D3 — Full Inference Pipeline

import cv2

def run_multi_model_inference(image_path, conf_override=None):
    """
    Run all 3 models on a single image.
    Returns: annotated image (BGR), final detections list, raw count per model.
    """
    image = cv2.imread(image_path)
    if image is None:
        raise ValueError(f'Could not load image: {image_path}')

    h, w = image.shape[:2]
    all_raw_detections = []
    model_raw_counts   = {}

    # Step 1: Run all 3 models
    for model_id, info in MODELS.items():
        conf_threshold = conf_override if conf_override else info['conf']
        results  = info['model'](image, conf=conf_threshold, iou=0.45, verbose=False)
        raw_count = 0

        for result in results:
            if result.boxes is None:
                continue
            for i in range(len(result.boxes)):
                raw_count += 1
                xyxy     = result.boxes.xyxy[i].cpu().numpy()
                conf     = float(result.boxes.conf[i])
                cls_id   = int(result.boxes.cls[i])
                cls_name = result.names.get(cls_id, f'class_{cls_id}')
                all_raw_detections.append({
                    'model_id'  : model_id,
                    'model_name': info['name'],
                    'bbox'      : [float(xyxy[0]), float(xyxy[1]), float(xyxy[2]), float(xyxy[3])],
                    'confidence': conf,
                    'class_id'  : cls_id,
                    'class_name': cls_name,
                    'color'     : info['color'],
                })
        model_raw_counts[model_id] = raw_count

    # Step 2: Cross-model NMS
    final_detections = cross_model_nms(all_raw_detections, iou_threshold=0.45)

    # Step 3: Draw bounding boxes
    annotated  = image.copy()
    font       = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.55

    for det in final_detections:
        x1, y1, x2, y2 = [int(v) for v in det['bbox']]
        color  = det['color']
        label  = f"{det['model_id'][-1].upper()}: {det['class_name']} {det['confidence']:.2f}"

        # Thicker box if multiple models agreed
        thickness = 3 if len(det.get('agreeing_models', [])) > 1 else 2
        cv2.rectangle(annotated, (x1, y1), (x2, y2), color, thickness)

        # Label background + text
        text_size = cv2.getTextSize(label, font, font_scale, 1)[0]
        label_y   = max(y1 - 5, text_size[1] + 5)
        cv2.rectangle(annotated,
                      (x1, label_y - text_size[1] - 4),
                      (x1 + text_size[0] + 4, label_y + 2),
                      color, -1)
        cv2.putText(annotated, label, (x1 + 2, label_y - 2),
                    font, font_scale, (255, 255, 255), 1, cv2.LINE_AA)

    return annotated, final_detections, model_raw_counts

print('✓ Inference pipeline ready.')

# CELL D4 — Visualization + Display Function

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

def display_results(image_path):
    """Run inference and display annotated result with detection table."""

    print(f'Processing: {image_path}')
    annotated, detections, raw_counts = run_multi_model_inference(image_path)

    fig, axes = plt.subplots(1, 2, figsize=(16, 7))

    orig = cv2.cvtColor(cv2.imread(image_path), cv2.COLOR_BGR2RGB)
    axes[0].imshow(orig)
    axes[0].set_title('Original Image', fontsize=13, fontweight='bold')
    axes[0].axis('off')

    ann = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)
    axes[1].imshow(ann)
    axes[1].set_title(f'Multi-Model Detection ({len(detections)} final detections)', fontsize=13, fontweight='bold')
    axes[1].axis('off')

    legend_patches = [
        mpatches.Patch(color=(1, 0.2, 0.2),   label=f"Model A — RDD2022 ({raw_counts.get('model_a', 0)} raw)"),
        mpatches.Patch(color=(0.2, 0.86, 0.2), label=f"Model B — Pothole-600 ({raw_counts.get('model_b', 0)} raw)"),
        mpatches.Patch(color=(0.2, 0.4, 1),    label=f"Model C — Kaggle ({raw_counts.get('model_c', 0)} raw)"),
    ]
    fig.legend(handles=legend_patches, loc='lower center', ncol=3,
               fontsize=10, framealpha=0.9, bbox_to_anchor=(0.5, -0.02))

    plt.tight_layout()
    plt.savefig('/content/result_annotated.jpg', bbox_inches='tight', dpi=120)
    plt.show()

    if detections:
        print(f"\n{'─'*65}")
        print(f"{'#':<4} {'Model':<12} {'Class':<20} {'Conf':>8} {'Consensus':>12}")
        print(f"{'─'*65}")
        for i, det in enumerate(detections, 1):
            agreeing  = det.get('agreeing_models', [det['model_id']])
            consensus = f"{len(agreeing)}/3 models"
            flag      = ' ★' if len(agreeing) > 1 else ''
            print(f"{i:<4} {det['model_id']:<12} {det['class_name']:<20} {det['confidence']:>8.4f} {consensus:>12}{flag}")
        print(f"{'─'*65}")
        print('★ = Multiple models agreed (strong signal)')
    else:
        print('\nNo potholes detected in this image.')

    return detections

print('✓ Display function ready.')

# CELL D5 — Test with Your Own Images
# Upload any road or pothole images to test the full pipeline.

from google.colab import files

print('Upload road/pothole images to test (multiple allowed):')
uploaded_test = files.upload()

for filename in uploaded_test.keys():
    test_path = f'/content/{filename}'
    with open(test_path, 'wb') as f:
        f.write(uploaded_test[filename])
    print(f"\n{'='*70}")
    detections = display_results(test_path)
    print(f"{'='*70}\n")

# CELL D6 — Test on Dataset Validation Images (no upload needed)
# Samples 2 images from each dataset's validation split.

import random

def test_on_val_images(n_per_dataset=2):
    test_sources = [
        (f'{WORKSPACE}/dataset_a/valid/images', 'Dataset A — RDD2022 Dashcam'),
        (f'{WORKSPACE}/dataset_b/valid/images', 'Dataset B — Pothole-600 Close-up'),
        (f'{DATASET_C_YOLO_DIR}/val/images',    'Dataset C — Kaggle Street'),
    ]
    for img_dir, source_name in test_sources:
        print(f"\n{'='*70}")
        print(f'Testing: {source_name}')
        print(f"{'='*70}")
        img_paths = list(Path(img_dir).glob('*.jpg')) + list(Path(img_dir).glob('*.png'))
        if not img_paths:
            print(f'No images found in {img_dir}')
            continue
        for img_path in random.sample(img_paths, min(n_per_dataset, len(img_paths))):
            display_results(str(img_path))

test_on_val_images(n_per_dataset=2)

"""---
## 💾 Save Inference Script to Drive

Exports a standalone `inference.py` — the exact file that Phase 2 (FastAPI backend) will import.  
No Colab dependency. Runs anywhere with `ultralytics` installed.
"""

# CELL E1 — Save inference.py to Google Drive

inference_script = '''
"""
Road Damage Multi-Model Inference — Standalone Module
Generated by: Road_Damage_MultiModel_Pipeline.ipynb
Usage: from inference import RoadDamageDetector
"""

import cv2
import numpy as np
from ultralytics import YOLO
from pathlib import Path


def compute_iou(box1, box2):
    x1, y1 = max(box1[0], box2[0]), max(box1[1], box2[1])
    x2, y2 = min(box1[2], box2[2]), min(box1[3], box2[3])
    intersection = max(0, x2 - x1) * max(0, y2 - y1)
    if intersection == 0:
        return 0.0
    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])
    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])
    return intersection / (area1 + area2 - intersection)


def cross_model_nms(detections, iou_threshold=0.45):
    if not detections:
        return []
    sorted_dets = sorted(detections, key=lambda x: x["confidence"], reverse=True)
    kept, suppressed = [], set()
    for i, det_i in enumerate(sorted_dets):
        if i in suppressed:
            continue
        det_i["agreeing_models"] = [det_i["model_id"]]
        for j, det_j in enumerate(sorted_dets):
            if j <= i or j in suppressed:
                continue
            if compute_iou(det_i["bbox"], det_j["bbox"]) > iou_threshold:
                det_i["agreeing_models"].append(det_j["model_id"])
                suppressed.add(j)
        kept.append(det_i)
    return kept


class RoadDamageDetector:
    MODEL_CONFIG = {
        "model_a": {"name": "RDD2022 Dashcam",   "color": (255, 50,  50),  "conf": 0.05},
        "model_b": {"name": "Pothole-600 Close",  "color": (50,  220, 50),  "conf": 0.10},
        "model_c": {"name": "Kaggle Street",      "color": (50,  100, 255), "conf": 0.05},
    }

    def __init__(self, weights_dir: str):
        self.models = {}
        weights = Path(weights_dir)
        for mid, fname in [("model_a", "model_a_rdd2022.pt"),
                           ("model_b", "model_b_pothole600.pt"),
                           ("model_c", "model_c_kaggle.pt")]:
            path = weights / fname
            if path.exists():
                self.models[mid] = YOLO(str(path))
                print(f"Loaded {mid}")
            else:
                print(f"Warning: {mid} not found at {path}")

    def predict(self, image_path: str) -> dict:
        image = cv2.imread(image_path)
        if image is None:
            raise ValueError(f"Cannot load: {image_path}")
        all_dets = []
        for mid, model in self.models.items():
            conf = self.MODEL_CONFIG[mid]["conf"]
            results = model(image, conf=conf, verbose=False)
            for result in results:
                if result.boxes is None:
                    continue
                for i in range(len(result.boxes)):
                    xyxy = result.boxes.xyxy[i].cpu().numpy()
                    all_dets.append({
                        "model_id":   mid,
                        "bbox":       [float(v) for v in xyxy],
                        "confidence": float(result.boxes.conf[i]),
                        "class_name": result.names[int(result.boxes.cls[i])],
                        "color":      self.MODEL_CONFIG[mid]["color"],
                    })
        final = cross_model_nms(all_dets)
        return {"detections": final, "count": len(final)}
'''

script_path = f'{DRIVE_SAVE_DIR}/inference.py'
with open(script_path, 'w') as f:
    f.write(inference_script)

print(f'✓ inference.py saved to Drive: {script_path}')
print('\n' + '🎉 ' * 20)
print('PHASE 1 COMPLETE!')
print('  ✓ Model A trained  → model_a_rdd2022.pt')
print('  ✓ Model B trained  → model_b_pothole600.pt')
print('  ✓ Model C trained  → model_c_kaggle.pt')
print('  ✓ Multi-model pipeline tested')
print('  ✓ inference.py saved for Phase 2 (FastAPI backend)')
print('\nNext: Phase 2 — Ensemble Fusion + Severity Classification')

# CELL DOWNLOAD — Zip all models + inference.py and download to local machine

import os
import zipfile
from google.colab import files
from pathlib import Path

ZIP_PATH = '/content/RoadDamageAI_Phase1.zip'

print("📦 Creating zip archive...")

with zipfile.ZipFile(ZIP_PATH, 'w', zipfile.ZIP_DEFLATED) as zipf:

    # ── Model weights ─────────────────────────────────────────────────
    for fname, label in [
        (MODEL_A_PATH, 'model_a_rdd2022.pt'),
        (MODEL_B_PATH, 'model_b_pothole600.pt'),
        (MODEL_C_PATH, 'model_c_kaggle.pt'),
    ]:
        if os.path.exists(fname):
            zipf.write(fname, f'weights/{label}')
            size_mb = os.path.getsize(fname) / 1e6
            print(f"  ✓ weights/{label} ({size_mb:.1f} MB)")
        else:
            print(f"  ✗ MISSING: {fname}")

    # ── inference.py ──────────────────────────────────────────────────
    inference_path = f'{DRIVE_SAVE_DIR}/inference.py'
    if os.path.exists(inference_path):
        zipf.write(inference_path, 'inference.py')
        print(f"  ✓ inference.py")
    else:
        print(f"  ✗ MISSING: inference.py")

    # ── Training plots from all 3 runs ────────────────────────────────
    for model_id in ['model_a_rdd2022', 'model_b_pothole600*', 'model_c_kaggle*']:
        import glob
        run_dirs = sorted(glob.glob(f'{WORKSPACE}/runs/{model_id}'))
        if run_dirs:
            run_dir = Path(run_dirs[-1])  # Latest run
            for plot_file in run_dir.glob('*.png'):
                zipf.write(str(plot_file), f'plots/{run_dir.name}/{plot_file.name}')
            print(f"  ✓ plots/{run_dir.name}/ (training curves)")

# ── Summary ───────────────────────────────────────────────────────────
zip_size = os.path.getsize(ZIP_PATH) / 1e6
print(f"\n📦 Archive ready: RoadDamageAI_Phase1.zip ({zip_size:.1f} MB)")

# List all contents
print("\nContents:")
with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    for info in z.infolist():
        print(f"  {info.filename}  ({info.file_size / 1e6:.1f} MB)")

# ── Download ──────────────────────────────────────────────────────────
print("\n⬇️  Starting download...")
files.download(ZIP_PATH)
print("✅ Download triggered.")