
"""
Road Damage Multi-Model Inference — Standalone Module
Generated by: Road_Damage_MultiModel_Pipeline.ipynb
Usage: from inference import RoadDamageDetector
"""

import cv2
import numpy as np
from ultralytics import YOLO
from pathlib import Path


def compute_iou(box1, box2):
    x1, y1 = max(box1[0], box2[0]), max(box1[1], box2[1])
    x2, y2 = min(box1[2], box2[2]), min(box1[3], box2[3])
    intersection = max(0, x2 - x1) * max(0, y2 - y1)
    if intersection == 0:
        return 0.0
    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])
    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])
    return intersection / (area1 + area2 - intersection)


def cross_model_nms(detections, iou_threshold=0.45):
    if not detections:
        return []
    sorted_dets = sorted(detections, key=lambda x: x["confidence"], reverse=True)
    kept, suppressed = [], set()
    for i, det_i in enumerate(sorted_dets):
        if i in suppressed:
            continue
        det_i["agreeing_models"] = [det_i["model_id"]]
        for j, det_j in enumerate(sorted_dets):
            if j <= i or j in suppressed:
                continue
            if compute_iou(det_i["bbox"], det_j["bbox"]) > iou_threshold:
                det_i["agreeing_models"].append(det_j["model_id"])
                suppressed.add(j)
        kept.append(det_i)
    return kept


class RoadDamageDetector:
    MODEL_CONFIG = {
        "model_a": {"name": "RDD2022 Dashcam",   "color": (255, 50,  50),  "conf": 0.05},
        "model_b": {"name": "Pothole-600 Close",  "color": (50,  220, 50),  "conf": 0.10},
        "model_c": {"name": "Kaggle Street",      "color": (50,  100, 255), "conf": 0.05},
    }

    def __init__(self, weights_dir: str):
        self.models = {}
        weights = Path(weights_dir)
        for mid, fname in [("model_a", "model_a_rdd2022.pt"),
                           ("model_b", "model_b_pothole600.pt"),
                           ("model_c", "model_c_kaggle.pt")]:
            path = weights / fname
            if path.exists():
                self.models[mid] = YOLO(str(path))
                print(f"Loaded {mid}")
            else:
                print(f"Warning: {mid} not found at {path}")

    def predict(self, image_path: str) -> dict:
        image = cv2.imread(image_path)
        if image is None:
            raise ValueError(f"Cannot load: {image_path}")
        all_dets = []
        for mid, model in self.models.items():
            conf = self.MODEL_CONFIG[mid]["conf"]
            results = model(image, conf=conf, verbose=False)
            for result in results:
                if result.boxes is None:
                    continue
                for i in range(len(result.boxes)):
                    xyxy = result.boxes.xyxy[i].cpu().numpy()
                    all_dets.append({
                        "model_id":   mid,
                        "bbox":       [float(v) for v in xyxy],
                        "confidence": float(result.boxes.conf[i]),
                        "class_name": result.names[int(result.boxes.cls[i])],
                        "color":      self.MODEL_CONFIG[mid]["color"],
                    })
        final = cross_model_nms(all_dets)
        return {"detections": final, "count": len(final)}
